### ISSUE TITLE
Hubitat child device turns off when device turns off

### ISSUE THREAD

**Issue by p0rt9** [InovelliUSA/Hubitat#27]
When using the new drivers that use the built in Hubitat child device. If the device is turned off locally or remotely the child device turns off. Thus clearing any notification.

**Comment by InovelliUSA** [comment]
This issue is resolved in the latest firmware release.

https://community.inovelli.com/t/firmware-v1-41-beta-lzw31-sn-dimmer-red-series-gen-2/2710
