### ISSUE TITLE
Please remove tiles sections

### ISSUE THREAD

**Issue by apwelsh** [InovelliUSA/Hubitat#6]
Hubitat does not use the tiles section of the code.  Please remove tiles from HE code to keep code waste to a minimum.  Thanks!

**Comment by sgrayban** [comment]
If you look at the code you will see it also supports SmartThings which DOES use tiles. That is why its there so Eric only has to maintain 1 file instead of 2... that's stopping code waste.

**Comment by apwelsh** [comment]
This is in the Hubitat namespace, and the zwave commands all declare 
hubitat.zwave.commands.associationv2.AssociationReport
Not the ST equivalent.  So, maybe I am missing something, but this to me appears to be ST compatible with refactoring.

**Comment by InovelliUSA** [comment]
Yeah sorry, I sometimes go back and forth between platforms while making changes to the code. Sometimes I'll make several changes in Hubitat and then bring them over to SmartThings. It is easier for me to keep as much code parity between the two versions so I'm not constantly adding code back and then removing it. If I release a final version I will permanently remove the non-Hubitat specific code.
