### ISSUE TITLE
Gen2 Drivers fail to update using Hubitat Package Manager (C7 Latest Firmware and up to date on HPM)

### ISSUE THREAD

**Issue by tweas** [InovelliUSA/Hubitat#63]
Received a notice that  I got an update for Innovelli Drivers this morning that will not update. Logs say "fatal error" and error message says to make sure the app/driver is not in use. I do have the innovelli drivers for my RED switches. But, I do not have the BLUE series installed. But, even if I did, what would be the point of automatic updates if I have to change all the drivers before I can run the updates. I do not think I can choose only the drivers I use out of the Series 2 drivers. 

Logs appear to be generic even though I have all the debug options enabled. If I could get more information, I would.

Tried twice on phone app(chrome?) and once on computer (firefox).

![1](https://github.com/InovelliUSA/Hubitat/assets/31957459/2a6d7e17-3509-4365-9c0e-d46e321e6f83)
![2](https://github.com/InovelliUSA/Hubitat/assets/31957459/881fe320-76a3-4f5c-92a0-425e03c160c5)
![3](https://github.com/InovelliUSA/Hubitat/assets/31957459/c87f560b-5447-4651-8db5-6b99969c9251)

**Comment by tweas** [comment]
Appears to be an issue with the code for the Bue Drivers:  https://community.hubitat.com/t/release-hubitat-package-manager-hpm-hubitatcommunity/94471/405?

**Comment by MarkA75160** [comment]
this has been fixed
