### ISSUE TITLE
VZM35-SN driver not available in Hubitat Package Manager

### ISSUE THREAD

**Issue by jamesallman** [InovelliUSA/Hubitat#78]
I have Hubitat Package Manager managing VZM31-SN driver updates but the VM35-SN driver is not yet available.  

It would be great to have it automatically updated as well.

**Comment by InovelliUSA** [comment]
Should already be there in driversG2:

![image](https://github.com/InovelliUSA/Hubitat/assets/37669481/d2f2d11c-4676-4a2b-8ff0-3309ba1d890e)

**Comment by jamesallman** [comment]
Thank you it was my error.  I assumed match up would pick it up and didn't realize I had to enable the new driver under "Modify a package" first.
